#!/bin/bash
echo "$VIRTUAL_HOST" > /etc/mailname
if [ ! -f /firstrundone ]; then
    if [ "$RELAY_HOST" != "" ]; then
        sed -ri "s/^relayhost\s*=.*$//g" /etc/postfix/main.cf
        echo "relayhost = $RELAY_HOST" >> /etc/postfix/main.cf
    fi
    if [ "$MASQ_DOMAINS" != "" ]; then
        echo "masquerade_domains = $MASQ_DOMAINS" >> /etc/postfix/main.cf
	fi
    echo "smtp_generic_maps = hash:/etc/postfix/generic" >> /etc/postfix/main.cf
    echo "root	no-reply@$MASQ_DOMAINS" >> /etc/postfix/generic
    postmap /etc/postfix/generic
    echo "done" >> /firstrundone
fi

service postfix start
set -e

cp -f /etc/php.ini /etc/php53/apache2/php.ini
cp -f /etc/php.ini /etc/php53/cli/php.ini
rm -f /var/run/apache2/*
source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND
